title: "Giovanni Ambrosioni"
theme: minima

# Replace with your actual GitHub Pages URL
url: "https://giovanniambrosioni.github.io"
baseurl: ""


# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Add a custom footer or modify/remove the existing one
# footer: "2024 Marco Badran"