title: "Giovanni Ambrosioni"
theme: minima

# Replace with your actual GitHub Pages URL
url: "https://giovanniambrosioni.github.io"
baseurl: ""


# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Add a custom footer or modify/remove the existing one
# footer: "2024 Marco Badran"

header_pages:
  - index.md
  - research.md
  - Talks.md
  - teaching.md
#  - blog.md
# La pagine blog e' nascosta. Se inserisci .../blog la puoi visualizzare. 
# I blog post si fanno creando un file .md in _blog, poi appare automaticamente.